### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by wannaphong** [brettatoms/zbar-ctypes#1]
I using "python setup.py install..
running install
Traceback (most recent call last):
  File "setup.py", line 39, in <module>
    setup(**config)
  File "C:\py3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\py3\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\py3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\py3\lib\site-packages\setuptools\command\install.py", line 67, in run

```
self.do_egg_install()
```

  File "C:\py3\lib\site-packages\setuptools\command\install.py", line 103, in do
_egg_install
    cmd.ensure_finalized()  # finalize before bdist_egg munges install cmd
  File "C:\py3\lib\distutils\cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "C:\py3\lib\site-packages\setuptools\command\easy_install.py", line 317,
in finalize_options
    self.index_url, search_path=self.shadow_path, hosts=hosts,
  File "C:\py3\lib\site-packages\setuptools\package_index.py", line 269, in __in
it__
    Environment.**init**(self,_args,_*kw)
  File "C:\py3\lib\site-packages\pkg_resources__init__.py", line 975, in **init
__
    self.scan(search_path)
  File "C:\py3\lib\site-packages\pkg_resources__init**.py", line 1005, in scan
    self.add(dist)
  File "C:\py3\lib\site-packages\pkg_resources__init__.py", line 1025, in add
    dists.sort(key=operator.attrgetter('hashcmp'), reverse=True)
TypeError: unorderable types: str() < NoneType()

Windows 8.1 64 Bit. Python 3.4.3 64 Bit.

**Comment by brettatoms** [comment]
I don't have a windows machine to try this on but I know you'll at least need to add support for loading the zbar library here:

https://github.com/brettatoms/zbar-ctypes/blob/master/zbar/_ctypes.py#L4

If you get it working please create a PR.

**Comment by wannaphong** [comment]
ok. I add a windows.
